apiVersion: v1
kind: Pod
metadata:
  name: busyboxtool
  labels:
    {{- include "busyboxtool.labels" . | nindent 4 }}
spec:
  selector:
      matchLabels:
        name: busyboxtool
  template:
    metadata:
      labels:
        name: busyboxtool
    spec:
      tolerations:
      - operator: Exists
      containers:
      - image: busybox:1.27.2
        imagePullPolicy: IfNotPresent
        name: busybox
        command: ["sh", "-c", "tail -f /dev/null"]
        terminationMessagePath: /dev/termination-log
