apiVersion: apps/v1
kind: Deployment
metadata:
  name: busyboxtool
  labels:
    {{- include "busyboxtool.labels" . | nindent 4 }}
spec:
  selector:
      matchLabels:
        name: busyboxtool
  template:
    metadata:
      labels:
        name: busyboxtool
    spec:
      tolerations:
      - operator: Exists
      containers:
      - image: busybox:1.27.2
        imagePullPolicy: IfNotPresent
        name: busybox
        command: ["sh", "-c", "tail -f /dev/null"]
        terminationMessagePath: /dev/termination-log
#        readinessProbe:
#          failureThreshold: 3
#          exec:
#            command:
#            - cat
#            - /test
#          initialDelaySeconds: 10
#          periodSeconds: 5
#          successThreshold: 1
#          timeoutSeconds: 3
