apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: busyboxtool
  labels:
    {{- include "busyboxtool.labels" . | nindent 4 }}
spec:
  selector:
      matchLabels:
        name: busyboxtool
  template:
    metadata:
      labels:
        name: busyboxtool
    spec:
      tolerations:
      - operator: Exists
      containers:
      - image: busybox:1.27.2
        imagePullPolicy: IfNotPresent
        name: busybox
        command: ["sh", "-c", "tail -f /dev/null"]
        terminationMessagePath: /dev/termination-log
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: https://www.baidu.com
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 3
