apiVersion: v1
kind: Service
metadata:
  name: {{ template "pgadmin.fullname" . }}
  labels:
    app: {{ template "pgadmin.fullname" . }}
    chart: {{ template "pgadmin.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ template "pgadmin.fullname" . }}
    release: {{ .Release.Name }}