apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}
    chart: {{ template "video.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  log4js_configuration.json: |
    {
      "appenders": {
        "console": {
          "type": "console"
        },
        "file": {
          "type": "dateFile",
          "filename": "all-the-logs.log"
        }
      },
      "categories": {
        "default": {
          "appenders": [
            "console"
          ],
          "level": "{{ .Values.config.log.DEFAULT_LEVEL }}"
        },
        "AMQPER": {
          "appenders": [
            "console"
          ],
          "level": "info"
        }
      }
    }