{{- $minport := .Values.config.MIN_PORT | int }}
{{- $maxport := .Values.config.MAX_PORT | add1 | int  }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "video.fullname" . }}-erizoagent
  labels:
    app: {{ template "video.fullname" . }}-erizoagent
    chart: {{ template "video.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
{{- range untilStep $minport $maxport 1 }}
    - protocol: UDP
      port: {{ . }}
      targetPort: {{ . }}
      nodePort: {{ . }}
      name: udp{{ . }}
{{- end }}
  selector:
    app: {{ template "video.fullname" . }}-erizoagent
    release: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "video.fullname" . }}-erizoagent
  labels:
    app: {{ template "video.fullname" . }}-erizoagent
    chart: {{ template "video.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "video.fullname" . }}-erizoagent
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "video.fullname" . }}-erizoagent
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: registry-gitlab
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - '--erizoAgent'
          ports:
{{- range untilStep $minport $maxport 1 }}
            - protocol: UDP
              containerPort: {{ . }}
              name: udp{{ . }}
{{- end }}
          env:
            - name: PUBLIC_IP
              value: '{{ .Values.config.PUBLIC_IP }}'
            - name: HTTP_PUBLIC_IP
              value: '{{ .Values.config.HTTP_PUBLIC_IP }}'
            - name: PRIVATE_PUBLIC_IP
              value: '{{ .Values.config.PRIVATE_PUBLIC_IP }}'
            - name: MIN_PORT
              value: '{{ .Values.config.MIN_PORT }}'
            - name: MAX_PORT
              value: '{{ .Values.config.MAX_PORT }}'
            - name: erizo_numIOWorkers
              value: '{{ .Values.config.erizo_numIOWorkers }}'
            - name: RABBIT_HOST
              value: '{{ template "video.fullname" . }}-rabbitmq'
            - name: RABBIT_PORT
              value: '5672'
          volumeMounts:
            - name: config-volume
              mountPath: /opt/licode/erizo_controller/log4js_configuration.json
              subPath: log4js_configuration.json
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-config
      # let video schedule on the same node with video database
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - {{ template "video.fullname" . }}-rabbitmq
              topologyKey: kubernetes.io/hostname
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
#     {{- with .Values.affinity }}
#       affinity:
# {{ toYaml . | indent 8 }}
#     {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}