{{- if .Values.ingress.enabled -}}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ template "video.fullname" . }}-basicexample-ingress
  labels:
    app: {{ template "video.fullname" . }}-basicexample
    chart: {{ template "video.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class | quote }}
    nginx.ingress.kubernetes.io/proxy-send-timeout: "36000"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "36000"
spec:
{{- if .Values.ingress.basicexample.host }}
  tls:
    - hosts: 
        - {{ .Values.ingress.basicexample.host }}
      secretName: {{ .Values.ingress.basicexample.secretName }}
{{- end }}
  rules:
  - http:
      paths:
      - path: /
        backend:
          {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
          service:
            name: {{ template "video.fullname" . }}-basicexample
            port:
              name: http
          {{- else }}
          serviceName: {{ template "video.fullname" . }}-basicexample
          servicePort: http
          {{- end }}
        {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
        pathType: ImplementationSpecific
        {{- end }}
{{- if .Values.ingress.basicexample.host }}
    host: {{ .Values.ingress.basicexample.host }}
{{- end }}
{{- end }}