apiVersion: v1
kind: Service
metadata:
  name: {{ template "video.fullname" . }}-mongodb
  labels:
    app: {{ template "video.fullname" . }}-mongodb
    chart: {{ template "video.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  #type: NodePort
  clusterIP: None
  ports:
    - protocol: TCP
      port: 27017
      targetPort: http
      name: http
  selector:
    app: {{ template "video.fullname" . }}-mongodb
    release: {{ .Release.Name }}
---
{{- if .Values.useLocalStore }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ template "video.fullname" . }}-mongodb-storage
  labels:
    app: {{ template "video.fullname" . }}-mongodb
    chart: {{ template "video.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "video.fullname" . }}-mongodb-volume
  labels:
    app: {{ template "video.fullname" . }}-mongodb
    chart: {{ template "video.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  capacity:
    storage: 10Gi
  # volumeMode field requires BlockVolume Alpha feature gate to be enabled.
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: {{ template "video.fullname" . }}-mongodb-storage
  local:
    path: {{ .Values.mongodb.dbpath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.nodename }}
{{- end }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "video.fullname" . }}-mongodb
  labels:
    app: {{ template "video.fullname" . }}-mongodb
    chart: {{ template "video.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ template "video.fullname" . }}-mongodb
  selector:
    matchLabels:
      app: {{ template "video.fullname" . }}-mongodb
      release: {{ .Release.Name }}
{{- if .Values.useLocalStore }}
  volumeClaimTemplates:
  - metadata:
      name: video-mongodb-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ template "video.fullname" . }}-mongodb-storage
      resources:
        requests:
          storage: 10Gi
{{- end }}
  template:
    metadata:
      labels:
        app: {{ template "video.fullname" . }}-mongodb
        release: {{ .Release.Name }}
    spec:
      # imagePullSecrets:
      #   - name: registry-gitlab
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
          imagePullPolicy: {{ .Values.mongodb.image.pullPolicy }}
          ports:
            - containerPort: 27017
              name: http
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # env:
          #   - name: MONGO_INITDB_ROOT_USERNAME
          #     value: root
          #   - name: MONGO_INITDB_ROOT_PASSWORD
          #     value: '123456'
          volumeMounts:
            - name: video-mongodb-volume
              mountPath:  /data/db
            {{- if not .Values.useLocalStore }}
              subPath: mongodb
            {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if not .Values.useLocalStore }}
      volumes:
        - name: video-mongodb-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-data-pvc
            readOnly: false
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
#     {{- with .Values.affinity }}
#       affinity:
# {{ toYaml . | indent 8 }}
#     {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}